namespace PatientAPI.Domain.DTOs
{
    public class PersonalInfoDto
    {
        public string PatientId { get; set; } = null!;// This will be generated by the ID generator
        public string FirstName { get; set; } = null!;
        public string LastName { get; set; } = null!;
        public int Age { get; set; }
        public string Gender { get; set; } = null!;
        public string Address { get; set; } = null!;
        public string Country { get; set; } = null!;
        public string State { get; set; } = null!;
        public string City { get; set; } = null!;
        public string Phone { get; set; } = "0000000000";
        public string Email { get; set; } = "";
    }
}
